# Generated by Django 5.0.2 on 2024-10-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="order_email",
            field=models.EmailField(default="example@email.com", max_length=254),
        ),
    ]
