# Generated by Django 5.0.2 on 2025-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth0_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="User", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("id", "name", "product_type")},
        ),
    ]
