services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Changed from 8000 to 8080
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - PORT=8080  # Added PORT environment variable
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app